version: '3'
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
  flask-server:
    build: ./flask-server
    ports:
      - "5000:5000"
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-test}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG-0} #1 with logs
      - HOSTNAME_EXTERNAL=localhost
      - DOCKER_HOST=unix:////var/run/docker.sock
      - services=s3:4567
      - port_web_ui:8082
      - debug=1
      - lambda_executor=${lambda_executor-}
      - aws_region=us-east-1
      - aws_access_key_id=test
      - aws_secret_access_key=test
