version: '3'

services:

  reviews:
    build: ./backend/reviews
    ports:
      - "8003:8003"
    volumes:
      - ./backend/reviews:/app
    depends_on:
      - localstack

  user-service:
    build: ./backend/user-service
    ports:
      - "8001:8001"
    volumes:
      - ./backend/user-service:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - localstack
      - financial-service

  inventory_management:
    build: ./backend/inventory_management
    ports:
      - "8002:8002"
    volumes:
      - ./backend/inventory_management:/app
    depends_on:
      - localstack

  orders:
    build: ./backend/orders
    ports:
      - "8004:8004"
    volumes:
      - ./backend/orders:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - localstack

  financial-service:
    build: ./backend/financial-service
    ports:
      - "8005:8005"
    volumes:
      - ./backend/financial-service:/app
    depends_on:
      - localstack
      - inventory_management
      - orders

  stripe-cli:
    image: stripe/stripe-cli
    command: listen --api-key "sk_test_51P3x1RL2VoulaBDdRpHDMZQCFlvnAmG1D1HRzjwnual8vUucfqdIRJiuMDGXOcVP5m6zwvaYPE6QzXiQkR3Hledx00yqj0pned" --forward-to financial-service:8005/webhook
    depends_on:
      - financial-service

  client:
    build: client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_OPTIONS=--openssl-legacy-provider
    depends_on:
      - user-service
      - inventory_management
      - orders
      - reviews

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "4566:4566"
      #- "127.0.0.1:4566:4566"            # LocalStack Gateway
      #- "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - services=s3,iam,dynamodb
      - DEBUG=1
      - HOSTNAME_EXTERNAL-localhost
      - DOCKER_HOST=unix:////var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
      - services=s3:4566
      - lambda_executor=${lambda_executor-}
      - aws_region=us-east-1
      - aws_access_key_id=test
      - aws_secret_accress_key=test
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  # stripe-cli:
  #   container_name: stripe-cli
  #   image: stripe/stripe-cli
  #   command: "listen --api-key ${STRIPE_API_KEY:rk_test_somelongkey***************} --device-name ${STRIPE_DEVICE_NAME:Name} --forward-to web:8000/payment/webhook/"
  #   # env_file:
  #   #   - stripe_cli.env
