version: '3.8'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - services=s3,iam,dynamodb
      - DEBUG=1
      - HOSTNAME_EXTERNAL-localhost
      - DOCKER_HOST=unix:////var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
      - services=s3:4566
      - lambda_executor=${lambda_executor-}
      - aws_region=us-east-1
      - aws_access_key_id=test
      - aws_secret_accress_key=test
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8004:8004"
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DYNAMODB_HOST=http://localstack:4566
    depends_on:
      - localstack
