version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2022.09
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            docker-compose -f ./docker-compose.test.yml up