version: 2.1

jobs:
  build-and-test:
    machine:
      enabled: true
      image: ubuntu-2004:202010-01

    working_directory: ~/repo

    steps:
      - checkout

      # Ensure Docker is installed and running
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: 'v2.25.0'
          command: |
            curl -sSL "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            mkdir -p ~/.docker/cli-plugins
            chmod +x ~/docker-compose
            mv ~/docker-compose ~/.docker/cli-plugins/docker-compose

      # Copy your Docker Compose YAML file into CircleCI's environment
      - run:
          name: Set up Docker Compose
          command: |
            mkdir -p ./backend/user-service
            echo 'version: "3"' > docker-compose.test.yml
            echo 'services:' >> docker-compose.test.yml
            echo '  user-service:' >> docker-compose.test.yml
            echo '    build: ./backend/user-service' >> docker-compose.test.yml
            echo '    ports:' >> docker-compose.test.yml
            echo '      - "8001:8001"' >> docker-compose.test.yml
            echo '    command: pytest' >> docker-compose.test.yml
            echo '    volumes:' >> docker-compose.test.yml
            echo '      - ./backend/user-service:/app' >> docker-compose.test.yml
            echo '    environment:' >> docker-compose.test.yml
            echo '      - FLASK_ENV=testing' >> docker-compose.test.yml
            echo '  localstack:' >> docker-compose.test.yml
            echo '    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"' >> docker-compose.test.yml
            echo '    image: localstack/localstack' >> docker-compose.test.yml
            echo '    environment:' >> docker-compose.test.yml
            echo '      - services=s3,iam,dynamodb' >> docker-compose.test.yml
            echo '      - DEBUG=1' >> docker-compose.test.yml
            echo '      - HOSTNAME_EXTERNAL=localhost' >> docker-compose.test.yml
            echo '      - DATA_DIR=/tmp/localstack/data' >> docker-compose.test.yml
            echo '      - services=s3:4566' >> docker-compose.test.yml
            echo '      - lambda_executor=${lambda_executor-}' >> docker-compose.test.yml
            echo '      - aws_region=us-east-1' >> docker-compose.test.yml
            echo '      - aws_access_key_id=test' >> docker-compose.test.yml
            echo '      - aws_secret_access_key=test' >> docker-compose.test.yml
            echo '    volumes:' >> docker-compose.test.yml
            echo '      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"' >> docker-compose.test.yml

      # Execute tests
      - run:
          name: Run tests
          command: |
            docker-compose -f docker-compose.test.yml up -d

      # Stop and remove containers
      - run:
          name: Cleanup
          command: |
            docker-compose down

workflows:
  version: 2
  build:
    jobs:
      - build-and-test
