version: 2.1

jobs:
  build-and-test:
    machine:
      enabled: true
      image: ubuntu-2004:202010-01

    working_directory: ~/repo

    steps:
      - checkout

      # Ensure Docker is installed and running
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: 'v2.25.0'
          command: |
            curl -sSL "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            mkdir -p ~/.docker/cli-plugins
            chmod +x ~/docker-compose
            mv ~/docker-compose ~/.docker/cli-plugins/docker-compose

      - setup_remote_docker

      - run:
          name: RUN tests
          command: docker-compose -f docker-compose.test.yml up -d

      # Stop and remove containers
      - run:
          name: Cleanup
          command: |
            docker-compose down

workflows:
  version: 2
  build:
    jobs:
      - build-and-test
