version: 2.1

orbs:
  docker: circleci/docker@2.6.0

jobs:
  build-and-test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.4.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - run:
          name: Build and start containers
          command: |
            docker-compose -f docker-compose.test.yml up --build -d
      - run:
          name: Check user-service logs
          command: |
            docker-compose -f docker-compose.test.yml logs user-service
      - run:
          name: List files in the user-service container
          command: |
            docker-compose -f docker-compose.test.yml exec user-service ls -al /app
            docker-compose -f docker-compose.test.yml exec user-service ls -al /app/tests
      - run:
          name: Run pytest
          command: |
            docker-compose -f docker-compose.test.yml exec user-service pytest /app/tests
      - run:
          name: Cleanup
          command: |
            docker-compose -f docker-compose.test.yml down

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
